library(arsenal)
library(dplyr)
library(readr)
library(reshape2)
library(gapminder)

company <- read.csv2("H:/ninte/Documents/R Workspace/Lab12/company2.csv", header = T)
View(company)
class(company)
company1 <- melt(company, id.vars = c("Age", "yer.service"))
company1[c(1:7),]
company2 <- dcast(company1, Age + yer.service ~ variable)
company2 [c(1:7),]
all.equal(company1, company2)
comparedf(company1, company2)
company[4:8,]
company_f <- filter(company, yer.service.OOO == 4)
company_fp <- company %>% filter(yer.service.OOO == 4)
comparedf(company_f, company_fp)
company %>% filter(yer.service.OOO == 4 & Age >= 26) %>% head(4)
company %>% slice(2:6)
company %>% arrange(yer.service.OOO)
company %>% arrange(yer.service)
company %>% arrange(desc(Age))
company %>% select(Sex, Age, Position)
company %>% select(contains("A"))
company %>% select(starts_with("y"))                 
company <- company %>% mutate(yer.service.percent = yer.service.OOO/yer.service * 100)
vvp <- gapminder
vvp1952 <- vvp %>% filter(year == 1952 & lifeExp > 60)
vvp1952 %>% arrange(desc(pop))
vvp %>% select(gdpPercap, continent, year)
vvp <- vvp %>% mutate(lifeExp.day = lifeExp*365)
vvp %>% group_by(country) %>% summarise(gdpPercap.country = mean(gdpPercap)) %>% arrange(desc(gdpPercap.country))
vvp_under1980 <- vvp %>% filter(year <= 1980)
vvp_after1980 <- vvp %>% filter(year > 1980)
vvp %>% select(lifeExp, country)
vvp <- vvp %>% group_by(country) %>% summarise(lifeExp.country = mean(lifeExp))
vvp2 <- inner_join(vvp_under1980, vvp_after1980, by = "country")
